# Generated by Django 5.0 on 2025-01-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
